# Generated by Django 5.0.1 on 2025-05-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_center', models.ImageField(blank=True, null=True, upload_to='home_page_images/', verbose_name='Logo trung trang')),
                ('image_top_right', models.ImageField(blank=True, null=True, upload_to='home_page_images/', verbose_name='Ảnh góc trên bên phải')),
                ('image_bottom_left', models.ImageField(blank=True, null=True, upload_to='home_page_images/', verbose_name='Ảnh góc dưới bên trái')),
                ('image_bottom_right', models.ImageField(blank=True, null=True, upload_to='home_page_images/', verbose_name='Ảnh góc dưới bên phải')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
