services:
  - type: web
    name: your-django-app-name
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn your_project_name.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: your_project_name.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: your-db-name
          property: connectionString
databases:
  - name: your-db-name
    region: oregon
    plan: free
